# Generated by Django 3.2.5 on 2021-08-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.blogger'),
        ),
    ]
