# Generated by Django 3.2.5 on 2021-08-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_blogger_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='user',
        ),
    ]
